
services:
  zenite:
    image: zenite-wordpress
    build: .
    container_name: zenite-wordpress
    restart: always
    ports:
      - "3980:80"
    env_file: .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - sigma-net
    depends_on:
      - zenite-db

  zenite-db:
    image: mariadb:10.6
    container_name: zenite-db
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:3954:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sigma-net

volumes:
  db_data:

networks:
  sigma-net:
    external: true
